### PR TITLE
start of d9 support

### PR DESCRIPTION
**Pull request by elizoller**
**GitHub Issue**: (https://github.com/Islandora/documentation/issues/1729)

# What does this Pull Request do?

This is a start of d9 support 

# What's new?
info file change and remove deprecated url() method

# How should this be tested?
make sure openseadragon still works

# Additional Notes:

# Interested parties
 @Islandora/8-x-committers

### CODE REVIEW

**Comment by elizoller** [comment]
i'm kind of at a loss for why `createFileUrl(FALSE)` would return null?

**Comment by jordandukart** [comment]
> i'm kind of at a loss for why `createFileUrl(FALSE)` would return null?

@elizoller, not sure what you experienced here? I tested the code on an 8 before and after the URLs I got generated were identical.

Similarly, dumping both methods out with `dsms` yield:

`url => http://localhost:8000/_flysystem/fedora/2020-12/51451703_10156721107980661_2882884170512596992_n.jpg`

`createFileUrl => http://localhost:8000/_flysystem/fedora/2020-12/51451703_10156721107980661_2882884170512596992_n.jpg`

**Review by jordandukart — APPROVED** [review]
Approved based upon what I saw, will wait for @elizoller to chime in here or Slack as to what may be up with `NULL` URLs.

**Review by qadan — APPROVED** [review]
looks fine, no compatibility issues across 8/9

**Pull request merged**
