### PR TITLE
Update compatibility to include Drupal 10.

### PR DESCRIPTION
**Pull request by rosiel**
**GitHub Issue**: (link)

https://github.com/Islandora/documentation/issues/2235

# What does this Pull Request do?

Makes Openseadragon Drupal 10 compatible.

# What's new?
A in-depth description of the changes made by this PR. Technical details and
 possible side effects.

* Changes x feature to such that y
* Added x
* Removed y
* Does this change require documentation to be updated?
* Does this change add any new dependencies?
* Does this change require any other modifications to be made to the repository
 (i.e. Regeneration activity, etc.)?
* Could this change impact execution of existing code?

# How should this be tested?

Install on Drupal 10 and give it an external Mirador URI.

# Additional Notes:
Any additional information that you think would be helpful when reviewing this
 PR.

# Interested parties
Tag (@ mention) interested parties or, if unsure, @Islandora/committers

### CODE REVIEW

**Review by alxp — CHANGES_REQUESTED** [review]
Just one small notice when running PHPUnit tests:

Testing /Users/alexanderoneill/Sites/d10/web/modules/contrib/openseadragon/tests
.....                                                               5 / 5 (100%)

Time: 00:05.333, Memory: 8.00 MB

OK (5 tests, 40 assertions)

Remaining self deprecation notices (5)

  5x: The Drupal\Tests\openseadragon\Kernel\IIIFManifestParserTest::$modules property must be declared protected. See https://www.drupal.org/node/2909426
    5x in DrupalListener::startTest from Drupal\Tests\Listeners

Alexanders-MBP:core alexanderoneill$

**Comment by rosiel** [comment]
i'll add D10 to the testing matrix first

**Comment by rosiel** [comment]
or after. whoops.

**Comment by rosiel** [comment]
I think that update [c357901](https://github.com/Islandora/openseadragon/pull/49/commits/c3579012d38640c4daed1f10c06bcd2383de1b1c)) should cover the deprecation notices you saw. The tests ran and I don't see any deprecation warnings in them now.

**Review by alxp — APPROVED** [review]

**Pull request merged**
