### PR TITLE
replace travis with github actions

### PR DESCRIPTION
**Pull request by elizoller**
**GitHub Issue**: (https://github.com/Islandora/documentation/issues/1798)

# What does this Pull Request do?
Converts to github actions
updates the badge
removes travis

# What's new?
* new CI runner

# How should this be tested?
* make sure the tests pass (i don't think they will until this PR is merged - but you can see them running over on the branch itself)
passed here: https://github.com/asulibraries/openseadragon/actions/runs/794109419

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Review by whikloj — APPROVED** [review]
👍

**Comment by whikloj** [comment]
@dannylamb need an owner here to remove the "required status". You can merge it too.

**Comment by rosiel** [comment]
Uh oh(?) it's failing on 7.4 / 9.1.5: https://github.com/Islandora/openseadragon/runs/2510287126?check_suite_focus=true 

`E: The repository 'https://packages.microsoft.com/repos/azure-cli focal Release' no longer has a Release file.
Error: Process completed with exit code 100.`

**Comment by elizoller** [comment]
i believe its ok, i just restarted it and it went all right

**Pull request merged**
